import turtle
turtle.shape('turtle')
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.left(90) 
turtle.forward(20) #first
turtle.end_fill()
turtle.penup()
turtle.goto(-5,-5)
turtle.pendown()
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90) 
turtle.forward(30) #second
turtle.penup()
turtle.goto(-10,-10)
turtle.pendown()
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90) 
turtle.forward(40) #third
turtle.penup()
turtle.goto(-15,-15)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50) #forth
